# Mosquitto MQTT Broker - Sistema Llamado de Enfermeras
# Puerto principal
listener 1883

# Autenticacion
allow_anonymous false
password_file /mosquitto/config/password.txt

# Persistencia
persistence true
persistence_location /mosquitto/data/

# Logs
log_dest stdout
log_type error
log_type warning
log_type notice
connection_messages true

# Limites
max_connections 100
max_queued_messages 1000
